### ISSUE TITLE
能否增加对TotemTimers Classic的美化支持

### ISSUE THREAD

**Issue by CmcnPro** [Witnesscm/NDui_Plus_Classic#1]
TotemTimers Classic 
[curseforge](https://www.curseforge.com/wow/addons/totemtimers-classic)
[github](https://github.com/Xianghar/TotemTimers_Classic)

该插件暂无BCC版本,但是有个第三方的fix
[GitHub](https://github.com/laytya/TotemTimers_Classic)

**Comment by Witnesscm** [comment]
添加了，可以测试一下

**Comment by CmcnPro** [comment]
感谢.TotemTimers classic已推出BCC版本,且测试通过.

**Comment by CmcnPro** [comment]
[TotemTimesr Classic](https://github.com/Xianghar/TotemTimers_Classic) 更新到了1.11版本
Ndui Plus 2.0.6版本的美化失效
![image](https://user-images.githubusercontent.com/11855767/120098128-b99f9380-c166-11eb-9800-5bbca1346324.png)

**Comment by Witnesscm** [comment]
如果装了Masque的话，在皮肤设置里对TotemTimers禁用试试

**Comment by CmcnPro** [comment]
禁用Masque解决相关问题
