### ISSUE TITLE
2.4.0-wrath版本和Auctionator的外观美化不兼容

### ISSUE THREAD

**Issue by tyrival** [Witnesscm/NDui_Plus_Classic#15]
...rface/AddOns/NDui_Plus/Modules/Skins/Auctionator.lua:207: attempt to index field 'ScrollFrame' (a nil value)
Count: 1

Call Stack:
[string "=[C]"]: ?
[string "@Interface/AddOns/NDui_Plus/Modules/Skins/Auctionator.lua"]:207: in function <...rface/AddOns/NDui_Plus/Modules/Skins/Auctionator.lua:201>
[string "=[C]"]: in function `AuctionHouseShown'
[string "@Interface/AddOns/Auctionator/Source_Classic/Initialize/Main.lua"]:18: in function <...ddOns/Auctionator/Source_Classic/Initialize/Main.lua:16>

**Comment by Witnesscm** [comment]
更新到2.4.1
