### ISSUE TITLE
是否考虑增加TANK监控

### ISSUE THREAD

**Issue by tyrival** [Witnesscm/NDui_Plus_Classic#4]
单独列出团队框架中标记为T的血条、目标、目标的目标，以前TBC就开放了这个API，现在ELVUI应该也可以显示。
我问了下NDUI的作者，他说不打算做这个，所以来问问大神愿不愿意开发这个功能。
<img width="329" alt="iShot2021-09-30 14 37 31" src="https://user-images.githubusercontent.com/8704241/135400218-dbdedee4-0974-436e-ac9a-366cd3e4faf2.png">

**Comment by Witnesscm** [comment]
有空我研究一下

**Comment by tyrival** [comment]
感谢大神，已收到
