### ISSUE TITLE
现在动作条渐隐后，鼠标放上去会显示，能否增加一个彻底隐藏的选项？

### ISSUE THREAD

**Issue by tyrival** [Witnesscm/NDui_Plus_Classic#5]
之前要彻底隐藏，要先禁用ndui的动作条，还得安装一个bartender4才行，大神能不能给加个彻底隐藏的选项？

**Comment by Witnesscm** [comment]
这个应该不会考虑，和动作条渐隐的设计目的不符，鼠标滑过是取消其他渐隐条件后最后的显示方式。
想要同时关闭ndui动作条和暴雪动作条的话，可以看看ndui隐藏暴雪动作条的代码
[NDui/Modules/ActionBar/Bars/Bar1.lua#L156](https://github.com/siweia/NDuiClassic/blob/8419e4c7dc982689a43ba455bf239fb65caaed19/Interface/AddOns/NDui/Modules/ActionBar/Bars/Bar1.lua#L156)
将这行代码移到if not C.db["Actionbar"]["Enable"] then return end上面一行

**Comment by tyrival** [comment]
好的，多谢指导。
现在我用的过程中遇到一个问题，比如我渐隐了一个动作条之后，划过其他动作条时，所有隐藏的动作条都会显示，这个能按照不同动作条进行区分渐隐/显示吗？
补充一个问题：我配置了渐隐之后，那个GCD结束后的闪光还在，这是怎么回事呀？

**Comment by Witnesscm** [comment]
全局渐隐就是这样，原理是将勾选的动作条设置为同一个父框体，通过控制父框体的透明度来实现，无法单独显隐单个动作条
GCD闪光的话，正常情况显隐一次后就会隐藏

[NDui/Config/Modules.lua#L13](https://github.com/siweia/NDuiClassic/blob/4d1b613fdbad0dec43f9ed8e0d01944d2bb68395/Interface/AddOns/NDui/Config/Modules.lua#L13)
ndui自带的动作条渐隐是另一个路子，每个动作条渐隐都是单独的，可以在这里手动开启，将需要渐隐的动作条的fader = nil改成fader = barFader
